name: Release to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Build
      run: | 
        python setup.py sdist
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
